### ISSUE TITLE
data in restored structure is recarray of recarrays

### ISSUE THREAD

**Issue by jslavin** [astrofrog/idlsave#1]
Hi Thomas,

I've been using idlsave for a while and there is one thing that is sort of an annoyance about it.  The IDL save file that I'm reading in was created from an IDL structure of form data = {'r':r, 'theta':theta,...} where each member is a 3-D array.  When I read it in with idlsave I get:
model = idlsave.read('../RL-plasma.sav')
helsphmod = model.data
But then helsphmod.shape gives (1,) -- helsphmod is a recarray of length 1. 
Same goes for helsphmod.r.  To get what I want I need to do something like:
r = helsphmod.r[0] which then has the shape of data.r
Why is that?  Wait, I think I got it -- it's because IDL structures can contain items of different lengths while recarrays must have all items of the same length, right?  I think it might be more understandable if the results were returned in a dictionary then.

Jon

**Comment by astrofrog** [comment]
Hi Jon,

Can you try to install the debug branch of idlsave and let me know if this fixes your problem? To install:

```
git clone git://github.com/astrofrog/idlsave.git
cd idlsave
git checkout debug
python setup.py install
```

Thanks,
Tom

**Comment by jslavin** [comment]
Hi Tom,

My system is on the HEAD LAN and I don't currently have git installed.  I could ask syshelp to install it, but is it possible to use github without git installed -- e.g. just downloading a tarball or something?  I'm wondering if Tom Aldcroft and others who use github and are on the HEAD LAN have git installed.  I was under the impression that they try to keep all the managed systems more or less uniform.

Jon

**Comment by astrofrog** [comment]
Go to the following <a href="https://github.com/astrofrog/idlsave/tree/debug">page</a>, then click on "Downloads" and then choose e.g. tar.gz under "Download Source". It will create a tar file on the fly.

**Comment by jslavin** [comment]
That's better.  Now when I read the IDL save file, the 'data' item is a numpy.core.records.record type with length equal to the number of items in the IDL structure.  I did notice that the array dimension order is reversed: original (in IDL) data.r is [220, 140, 79], after restoring with idlsave: data.r.shape is (79,140,220).  Was that on purpose to accommodate the different array index ordering in IDL vs. python?

**Comment by astrofrog** [comment]
Yes, the different index order is normal. If this is a problem, you can always just append <code>.transpose()</code> to the array to reverse the order.
