### ISSUE TITLE
Be less verbose

### ISSUE THREAD

**Issue by Nikratio** [astrofrog/idlsave#2]
Hi,

Thanks for working on IDLSave, it seems like a great tool so far. 

However, I really wish the read() method wouldn't dump so much text by default. This is probably useful when using it interactively, but really annoying when using it in a script. It would be great if all the output could be made optional.

**Comment by astrofrog** [comment]
The output is indeed verbose by default, but can be turned off with by passing `verbose=False` to `read(...)`. I think that in the next stable release, the default behavior might change to be `False` by default, as you are requesting.

**Comment by Nikratio** [comment]
Great, thanks!
