### ISSUE TITLE
"Exception: VARSTART is not 7"

### ISSUE THREAD

**Issue by tomr-stargazer** [astrofrog/idlsave#4]
Hi all,
I'm having the following issue with IDLsave. 

``` IDL
IDL> save, filename='doesthiswork.dat'
```

/Users/admin/Desktop/ipython -pylab
Enthought Python Distribution -- http://www.enthought.com

Python 2.7.1 |EPD 7.0-2 (32-bit)| (r271:86832, Dec  3 2010, 15:41:32) 
Type "copyright", "credits" or "license" for more information.

IPython 0.10.1 -- An enhanced Interactive Python.

  Welcome to pylab, a matplotlib-based Python environment.
  For more information, type 'help(pylab)'.

``` python
In [1]: import idlsave

In [4]: idlsave.__version__
Out[4]: '0.9.6'

In [2]: bob = idlsave.read( 'doesthiswork.dat' )
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)

/Users/admin/Desktop/<ipython console> in <module>()

/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/idlsave/idlsave.pyc in read(file_name, idict, python_dict, uncompressed_file_name, verbose)
    702     # Loop through records, and add them to the list

    703     while True:
--> 704         r = _read_record(f)
    705         records.append(r)
    706         if 'end' in r:

/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/idlsave/idlsave.pyc in _read_record(f)
    330         varstart = _read_long(f)
    331         if varstart <> 7:
--> 332             raise Exception("VARSTART is not 7")
    333 
    334         if rectypedesc['structure']:

Exception: VARSTART is not 7
```

**Comment by astrofrog** [comment]
Could you send the file `doesthiswork.dat` to thomas.robitaille@gmail.com? (if it's not too big). Otherwise, could you send a full script to produce a problematic file? Finally, what IDL version are you using?

**Comment by tomr-stargazer** [comment]
I will send it over. I am using IDL version 7 but several variables were created from IDL 8 (which may be the source of the problem).

**Comment by astrofrog** [comment]
Sorry for the delay - I think this should be fixed in ad5596134fa7e1960017 - can you confirm?

**Comment by daddeptr** [comment]
Hi there,
I think I'm having the same issue again with the latest version of idlsave part of scipy.io. I see that !=7 has been reintroduced, not sure if it's still causing troubles.
Anyone with the same problem?
Thanks
D

**Comment by astrofrog** [comment]
@daddeptr - I may have forgotten to port this change to `scipy.io.idl` - I will check today

**Comment by astrofrog** [comment]
Indeed I had forgotten - have now opened a PR on scipy: https://github.com/scipy/scipy/pull/4126

In the mean time, best use the standalone version since it will take a while for the scipy fixes to make it to the next release.
