### ISSUE TITLE
Error: invalid mode ('rb') 

### ISSUE THREAD

**Issue by OthmanB** [astrofrog/idlsave#5]
Hi, 

I have the following issue with some files only (IDL version issue?).  I use either IDL 7 or IDL 6.4. If you need the original file, I can send it. It contains arrays and structures.

Cheers,

Othman Benomar
## s=idlsave.read('n_param1.sav')

IOError                                   Traceback (most recent call last)
C:\Users\Benomar.xy\startups<ipython console> in <module>()
C:\Python26\lib\site-packages\idlsave\idlsave.pyc in read(file_name, idict, python_dict, uncompressed_file_name, verbose)
    624
    625     # Open the IDL file
--> 626     f = file(file_name, 'rb')
    627
    628     # Read the signature, which should be 'SR'
IOError: [Errno 22] invalid mode ('rb') or filename: 'n_param1.sav'

**Comment by astrofrog** [comment]
I'm going to close this - if this is still an issue, it should be opened in the [scipy](https://github.com/scipy/scipy) repository since this code lives there now (as scipy.io.idl)
